# Generated by Django 3.1 on 2020-08-20 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20200818_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alias',
            options={'ordering': ['-date', 'name']},
        ),
    ]
