# Generated by Django 3.1 on 2020-08-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alias_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alias',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
