# Generated by Django 3.1 on 2020-08-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_remove_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
